# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20170907_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-publish', '-updated']},
        ),
    ]
