# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category'),
        ),
    ]
