# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='offer',
        ),
    ]
