# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
