# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='article_1',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='article_10',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='article_2',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='article_3',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='article_4',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='article_5',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='article_6',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='article_7',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='article_8',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='article_9',
        ),
    ]
