# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(),
        ),
    ]
