# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20170911_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='slug',
        ),
    ]
