# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_remove_newsletter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
